/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recomendadorpeliculas;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class jfDetalleMovie extends javax.swing.JFrame {

    /**
     * Creates new form jfDetalleMovie
     */
    public jfDetalleMovie() {
        initComponents();
        setLocationRelativeTo(null);  
    }
    
    private int x;
    private int y;
    JFrame FormaPadre;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btCerrar2 = new javax.swing.JButton();
        btMiminizar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlTItle = new javax.swing.JLabel();
        jlDirector = new javax.swing.JLabel();
        jlActor1 = new javax.swing.JLabel();
        jlActor2 = new javax.swing.JLabel();
        jlActor3 = new javax.swing.JLabel();
        jlDuration = new javax.swing.JLabel();
        jlLink = new javax.swing.JLabel();
        jlYear = new javax.swing.JLabel();
        jlStars = new javax.swing.JLabel();
        jbStars = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jlGender = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        btCerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        btCerrar2.setAlignmentY(0.0F);
        btCerrar2.setAutoscrolls(true);
        btCerrar2.setBorder(null);
        btCerrar2.setBorderPainted(false);
        btCerrar2.setContentAreaFilled(false);
        btCerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCerrar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCerrar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCerrar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCerrar2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCerrar2MouseReleased(evt);
            }
        });

        btMiminizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/miminizar.png"))); // NOI18N
        btMiminizar1.setToolTipText("");
        btMiminizar1.setAlignmentY(0.0F);
        btMiminizar1.setAutoscrolls(true);
        btMiminizar1.setBorder(null);
        btMiminizar1.setBorderPainted(false);
        btMiminizar1.setContentAreaFilled(false);
        btMiminizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMiminizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMiminizar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMiminizar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMiminizar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMiminizar1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btMiminizar1MouseReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        jLabel1.setFont(new java.awt.Font("Jalane_light", 1, 48)); // NOI18N
        jLabel1.setText("Movie");

        jLabel3.setFont(new java.awt.Font("Jalane_light", 1, 48)); // NOI18N
        jLabel3.setText("Recommender");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btMiminizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMiminizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Movie Title:");
        jLabel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Director Name: ");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setText("Actor 1 Name:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel6.setText("Actor 2 Name:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel7.setText("Actor 3 Name:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel8.setText("Duration:");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel9.setText("IMDB Link:");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel10.setText("Year:");
        jLabel10.setToolTipText("");

        jlTItle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlTItle.setText("Movie Title:");
        jlTItle.setToolTipText("");

        jlDirector.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlDirector.setText("Director Name: ");
        jlDirector.setToolTipText("");

        jlActor1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlActor1.setText("Actor 1 Name:");
        jlActor1.setToolTipText("");

        jlActor2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlActor2.setText("Actor 2 Name:");
        jlActor2.setToolTipText("");

        jlActor3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlActor3.setText("Actor 3 Name:");
        jlActor3.setToolTipText("");

        jlDuration.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlDuration.setText("Duration:");
        jlDuration.setToolTipText("");

        jlLink.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlLink.setText("IMDB Link:");
        jlLink.setToolTipText("");

        jlYear.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlYear.setText("Year:");
        jlYear.setToolTipText("");

        jlStars.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jlStars.setPreferredSize(new java.awt.Dimension(67, 17));

        jbStars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/0.png"))); // NOI18N
        jbStars.setBorderPainted(false);
        jbStars.setContentAreaFilled(false);
        jbStars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStarsActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel19.setText("Genders:");
        jLabel19.setToolTipText("");

        jlGender.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jlGender.setText("Genders:");
        jlGender.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbStars, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)))))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlGender, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLink, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlYear, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTItle, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlActor3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlActor2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlActor1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlTItle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlDirector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlActor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlActor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlActor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jlGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jbStars, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStars, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrar2MouseClicked
        try{
            FormaPadre.setVisible(true);
            this.dispose();
            setLocationRelativeTo(null);  
        }catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_btCerrar2MouseClicked

    private void btCerrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrar2MouseEntered
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrarFocus.png"));
        btCerrar2.setIcon(Img);
    }//GEN-LAST:event_btCerrar2MouseEntered

    private void btCerrar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrar2MouseExited
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrar.png"));
        btCerrar2.setIcon(Img);
    }//GEN-LAST:event_btCerrar2MouseExited

    private void btCerrar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrar2MousePressed
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrarClick.png"));
        btCerrar2.setIcon(Img);
    }//GEN-LAST:event_btCerrar2MousePressed

    private void btCerrar2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrar2MouseReleased
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrarFocus.png"));
        btCerrar2.setIcon(Img);
    }//GEN-LAST:event_btCerrar2MouseReleased

    private void btMiminizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizar1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btMiminizar1MouseClicked

    private void btMiminizar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizar1MouseEntered
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizarFocus.png"));
        btMiminizar1.setIcon(Img);
    }//GEN-LAST:event_btMiminizar1MouseEntered

    private void btMiminizar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizar1MouseExited
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizar.png"));
        btMiminizar1.setIcon(Img);
    }//GEN-LAST:event_btMiminizar1MouseExited

    private void btMiminizar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizar1MousePressed
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizarClick.png"));
        btMiminizar1.setIcon(Img);
    }//GEN-LAST:event_btMiminizar1MousePressed

    private void btMiminizar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizar1MouseReleased
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizarFocus.png"));
        btMiminizar1.setIcon(Img);
    }//GEN-LAST:event_btMiminizar1MouseReleased

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel6MousePressed

    private void jbStarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbStarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfDetalleMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfDetalleMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfDetalleMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfDetalleMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfDetalleMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar2;
    private javax.swing.JButton btMiminizar1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbStars;
    private javax.swing.JLabel jlActor1;
    private javax.swing.JLabel jlActor2;
    private javax.swing.JLabel jlActor3;
    private javax.swing.JLabel jlDirector;
    private javax.swing.JLabel jlDuration;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlLink;
    private javax.swing.JLabel jlStars;
    private javax.swing.JLabel jlTItle;
    private javax.swing.JLabel jlYear;
    // End of variables declaration//GEN-END:variables

    private void ErrorMessage(String error){
        JOptionPane.showMessageDialog(null, error, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void InicializarForma(MovieData peli, JFrame formaPadre){
        FormaPadre = formaPadre;
        jlTItle.setText(peli._movie_title);
        jlActor1.setText(peli._actor_1_name);
        jlActor2.setText(peli._actor_2_name);
        jlActor3.setText(peli._actor_3_name);
        jlDirector.setText(peli._director_name);
        jlDuration.setText(String.valueOf(peli._duration) + " min.");
        jlGender.setText("...");
        jlLink.setText(peli._movie_imdb_link);
        jlYear.setText(String.valueOf(peli._title_year));
        jlGender.setText(peli.genders());
        ColocarEstrellas(peli._imdb_score);
    }
    
    private void ColocarEstrellas(double rate)
    {
        jlStars.setText(String.valueOf(rate)+ " / 10");
        ImageIcon Img;
        if (rate < 0.5) {
            Img = new ImageIcon(getClass().getResource("/Img/0.png"));
        }else if(rate >= 0.5 && rate < 1.5){
            Img = new ImageIcon(getClass().getResource("/Img/1.png"));
        }else if(rate >= 1.5 && rate < 2.5){
            Img = new ImageIcon(getClass().getResource("/Img/2.png"));
        }else if(rate >= 2.5 && rate < 3.5){
            Img = new ImageIcon(getClass().getResource("/Img/3.png"));
        }else if(rate >= 3.5 && rate < 4.5){
            Img = new ImageIcon(getClass().getResource("/Img/4.png"));
        }else if(rate >= 4.5 && rate < 5.5){
            Img = new ImageIcon(getClass().getResource("/Img/5.png"));
        }else if(rate >= 5.5 && rate < 6.5){
            Img = new ImageIcon(getClass().getResource("/Img/6.png"));
        }else if(rate >= 6.5 && rate < 7.5){
            Img = new ImageIcon(getClass().getResource("/Img/7.png"));
        }else if(rate >= 7.5 && rate < 8.5){
            Img = new ImageIcon(getClass().getResource("/Img/8.png"));
        }else if(rate >= 8.5 && rate < 9.5){
            Img = new ImageIcon(getClass().getResource("/Img/9.png"));
        }else{
            Img = new ImageIcon(getClass().getResource("/Img/10.png"));
        }
        
        jbStars.setIcon(Img);
    }
}
