/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recomendadorpeliculas;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class jfRecomender extends javax.swing.JFrame {

    /**
     * Creates new form jfRecomender
     */
    public jfRecomender() {
        initComponents();
        setLocationRelativeTo(null);  
        jsAño.setValue(1916);
    }
    
    private int x;
    private int y;
    DefaultListModel dimGood = new DefaultListModel();
    DefaultListModel dimBad = new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btCerrar = new javax.swing.JButton();
        btMiminizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlGenerosPreferidos = new javax.swing.JList<>();
        jcbGenerosPreferidos = new javax.swing.JComboBox<>();
        jbAñadirGeneroPreferido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jsEdad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jbIngresar = new javax.swing.JButton();
        jbRemoverGeneroPreferido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlGenerosMenosPreferidos = new javax.swing.JList<>();
        jcbGenerosNoPreferidos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jsAño = new javax.swing.JSpinner();
        jbAñadirGeneroMenosPreferido = new javax.swing.JButton();
        jbRemoverGeneroMenosPreferido = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar.png"))); // NOI18N
        btCerrar.setAlignmentY(0.0F);
        btCerrar.setAutoscrolls(true);
        btCerrar.setBorder(null);
        btCerrar.setBorderPainted(false);
        btCerrar.setContentAreaFilled(false);
        btCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCerrarMouseReleased(evt);
            }
        });

        btMiminizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/miminizar.png"))); // NOI18N
        btMiminizar.setToolTipText("");
        btMiminizar.setAlignmentY(0.0F);
        btMiminizar.setAutoscrolls(true);
        btMiminizar.setBorder(null);
        btMiminizar.setBorderPainted(false);
        btMiminizar.setContentAreaFilled(false);
        btMiminizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMiminizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMiminizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMiminizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMiminizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMiminizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btMiminizarMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Jalane_light", 1, 40)); // NOI18N
        jLabel6.setText("Recommender");

        jLabel7.setFont(new java.awt.Font("Jalane_light", 1, 40)); // NOI18N
        jLabel7.setText("Movie");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btMiminizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMiminizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ingrese sus 3 géneros preferidos:");

        jlGenerosPreferidos.setToolTipText("");
        jScrollPane1.setViewportView(jlGenerosPreferidos);

        jcbGenerosPreferidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Fantasy", "Sci-Fi", "Thriller", "Documentary", "Romance", "Animation", "Comedy", "Family", "Musical", "Mystery", "Western", "Drama", "History", "Sport", "Crime", "Horror", "War", "Biography", "Music", "Game-Show", "Reality-TV", "News", "Short", "Film-Noir" }));

        jbAñadirGeneroPreferido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add.png"))); // NOI18N
        jbAñadirGeneroPreferido.setBorderPainted(false);
        jbAñadirGeneroPreferido.setContentAreaFilled(false);
        jbAñadirGeneroPreferido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñadirGeneroPreferidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Edad: ");

        jLabel4.setText("Nombre: ");

        jbIngresar.setBackground(new java.awt.Color(255, 255, 255));
        jbIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/jplay.png"))); // NOI18N
        jbIngresar.setToolTipText("");
        jbIngresar.setAutoscrolls(true);
        jbIngresar.setBorderPainted(false);
        jbIngresar.setContentAreaFilled(false);
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        jbRemoverGeneroPreferido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/remove.png"))); // NOI18N
        jbRemoverGeneroPreferido.setBorderPainted(false);
        jbRemoverGeneroPreferido.setContentAreaFilled(false);
        jbRemoverGeneroPreferido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverGeneroPreferidoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlGenerosMenosPreferidos);

        jcbGenerosNoPreferidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Fantasy", "Sci-Fi", "Thriller", "Documentary", "Romance", "Animation", "Comedy", "Family", "Musical", "Mystery", "Western", "Drama", "History", "Sport", "Crime", "Horror", "War", "Biography", "Music", "Game-Show", "Reality-TV", "News", "Short", "Film-Noir" }));

        jLabel2.setText("Ingrese 3 géneros menos preferidos:");

        jLabel5.setText("Año Recurrente:");

        jsAño.setName(""); // NOI18N

        jbAñadirGeneroMenosPreferido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add.png"))); // NOI18N
        jbAñadirGeneroMenosPreferido.setBorderPainted(false);
        jbAñadirGeneroMenosPreferido.setContentAreaFilled(false);
        jbAñadirGeneroMenosPreferido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñadirGeneroMenosPreferidoActionPerformed(evt);
            }
        });

        jbRemoverGeneroMenosPreferido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/remove.png"))); // NOI18N
        jbRemoverGeneroMenosPreferido.setBorderPainted(false);
        jbRemoverGeneroMenosPreferido.setContentAreaFilled(false);
        jbRemoverGeneroMenosPreferido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverGeneroMenosPreferidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbAñadirGeneroPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbRemoverGeneroPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jcbGenerosPreferidos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbRemoverGeneroMenosPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbAñadirGeneroMenosPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jcbGenerosNoPreferidos, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsAño, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jbIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jsAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbGenerosPreferidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGenerosNoPreferidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAñadirGeneroMenosPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRemoverGeneroMenosPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbAñadirGeneroPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jbRemoverGeneroPreferido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jbIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErrorMessage(String error)
    {
        JOptionPane.showMessageDialog(null, error, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void jbAñadirGeneroPreferidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñadirGeneroPreferidoActionPerformed
        try {
            if (dimGood.getSize() == 3){
                throw new Exception("Solo se puede seleccionar un máximo de 3 generos preferidos");
            }
            
            String preferido = String.valueOf(jcbGenerosPreferidos.getSelectedItem());
                
            if (dimGood.contains(preferido)) {
                throw new Exception("El género:  " + preferido + " ya fue selecciondo.");
            }
            
            if (dimBad.contains(preferido)) {
                throw new Exception("El género:  " + preferido + " ya fue selecciondo como un genéro poco preferdio.");
            }
            
            dimGood.addElement(preferido);
            jlGenerosPreferidos.setModel(dimGood);
            
        } catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jbAñadirGeneroPreferidoActionPerformed

    private void jbAñadirGeneroMenosPreferidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñadirGeneroMenosPreferidoActionPerformed
        try {
            if (dimBad.getSize() == 3){
                throw new Exception("Solo se puede seleccionar un máximo de 3 generos poco preferidos");
            }
            
            String pocoPreferido = String.valueOf(jcbGenerosNoPreferidos.getSelectedItem());
            
            if (dimGood.contains(pocoPreferido)) {
                throw new Exception("El género:  " + pocoPreferido + " ya fue selecciondo.");
            }
            
            if (dimBad.contains(pocoPreferido)) {
                throw new Exception("El género:  " + pocoPreferido + " ya fue selecciondo como un genéro preferdio.");
            }
            
            dimBad.addElement(pocoPreferido);
            jlGenerosMenosPreferidos.setModel(dimBad);
        } catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jbAñadirGeneroMenosPreferidoActionPerformed

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        try {
            int año = Integer.parseInt(String.valueOf(jsAño.getValue()));
            if (año < 1916 || año > 2016) 
            {
                throw new Exception("El año debe de estar entre 1916 y 2016");
            }
            
            if (String.valueOf(jtfUser.getText()).isEmpty()) {
                throw new Exception("Ingrese un usuario.");
            }
            
            if (dimGood.getSize() < 3) {
                throw new Exception("Ingrese sus 3 géneros de preferencia.");
            }
            
            if (dimBad.getSize() < 3) {
                throw new Exception("Ingrese sus 3 géneros de poca preferencia.");
            }
            
            long[] UserVector = new long[185];
            int edad = Integer.parseInt(String.valueOf(jsEdad.getValue()));
            
            if (edad < 0) {
                throw new Exception("Ingrese su edad.");
            }
            
            //Likes
            for (int i = 0; i < 4; i++) {
                UserVector[i] = 10;
            }

            //Generos
            for (int i = 4; i < 30; i++) {
                String genero = String.valueOf(jcbGenerosPreferidos.getItemAt(i-4));
                if (dimGood.contains(genero)) {
                    UserVector[i] = 30;
                }
                else if (dimBad.contains(genero)){
                    UserVector[i] = -60;
                }
                else{
                    UserVector[i] = 0;
                }
            }

            //Clasiicación
            for (int i = 30; i < 48; i++) {
                UserVector[i] = 0;
            }

            UserVector[30] = 65;
            UserVector[35] = 65;
            UserVector[36] = 65;
            UserVector[41] = 65;
            UserVector[46] = 65;

            if (edad >= 1 && edad<=7) {
                UserVector[31] = 65;
            }

            if (edad >= 8 && edad<=12) {
                UserVector[32] = 65;
                UserVector[37] = 65;
            }

            if (edad >= 13 && edad<=14) {
                UserVector[33] = 65;
            }

            if (edad >= 18) {
                UserVector[34] = 65;
                UserVector[42] = 65;
                UserVector[39] = 65;
            }

            if (edad >= 13 && edad<=16) {
                UserVector[38] = 65;
            }

            if (edad > 14) {
                UserVector[40] = 65;
            }

            if (edad > 10) {
                UserVector[43] = 65;
            }

            if (edad >= 6) {
                UserVector[44] = 65;
            }

            if (edad < 6) {
                UserVector[45] = 65;
            }

            if (edad >= 21) {
                UserVector[47] = 65;
            }

            //Otros
            for (int i = 48; i < 185; i++) {
                UserVector[i] = 1;
            }
            
            jfPrincipal Nuevo = new jfPrincipal();
            Nuevo.setVisible(true);
            Nuevo.InicializarForma(UserVector,this, año);
            Nuevo.Recomendar();
            
            this.dispose(); 
            
        } catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
        
    }//GEN-LAST:event_jbIngresarActionPerformed

    private void jbRemoverGeneroMenosPreferidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverGeneroMenosPreferidoActionPerformed
        try {
            int pos = jlGenerosMenosPreferidos.getSelectedIndex();
            if (pos < 0) {
                throw new Exception("Debe de seleccionar un género para poder eliminarlo");
            }
            dimBad.remove(pos);
        } catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jbRemoverGeneroMenosPreferidoActionPerformed

    private void jbRemoverGeneroPreferidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverGeneroPreferidoActionPerformed
        try {
            int pos = jlGenerosPreferidos.getSelectedIndex();
            if (pos < 0) {
                throw new Exception("Debe de seleccionar un género para poder eliminarlo");
            }
            dimGood.remove(pos);
            
        } catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jbRemoverGeneroPreferidoActionPerformed

    private void btCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseClicked
        try{
            if (JOptionPane.showConfirmDialog(rootPane,
                "¿Realmente desea salir del sistema?",
                "Salir del sistema",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == 0){
                System.exit(0);
            }
        }catch (Exception e) {
            ErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_btCerrarMouseClicked

    private void btCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseEntered
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrarFocus.png"));
        btCerrar.setIcon(Img);
    }//GEN-LAST:event_btCerrarMouseEntered

    private void btCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseExited
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrar.png"));
        btCerrar.setIcon(Img);
    }//GEN-LAST:event_btCerrarMouseExited

    private void btCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMousePressed
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrarClick.png"));
        btCerrar.setIcon(Img);
    }//GEN-LAST:event_btCerrarMousePressed

    private void btCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarMouseReleased
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/cerrarFocus.png"));
        btCerrar.setIcon(Img);
    }//GEN-LAST:event_btCerrarMouseReleased

    private void btMiminizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizarMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btMiminizarMouseClicked

    private void btMiminizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizarMouseEntered
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizarFocus.png"));
        btMiminizar.setIcon(Img);
    }//GEN-LAST:event_btMiminizarMouseEntered

    private void btMiminizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizarMouseExited
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizar.png"));
        btMiminizar.setIcon(Img);
    }//GEN-LAST:event_btMiminizarMouseExited

    private void btMiminizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizarMousePressed
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizarClick.png"));
        btMiminizar.setIcon(Img);
    }//GEN-LAST:event_btMiminizarMousePressed

    private void btMiminizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMiminizarMouseReleased
        ImageIcon Img = new ImageIcon(getClass().getResource("/Img/miminizarFocus.png"));
        btMiminizar.setIcon(Img);
    }//GEN-LAST:event_btMiminizarMouseReleased

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfRecomender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfRecomender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfRecomender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfRecomender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfRecomender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btMiminizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JButton jbAñadirGeneroMenosPreferido;
    private javax.swing.JButton jbAñadirGeneroPreferido;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JButton jbRemoverGeneroMenosPreferido;
    private javax.swing.JButton jbRemoverGeneroPreferido;
    private javax.swing.JComboBox<String> jcbGenerosNoPreferidos;
    private javax.swing.JComboBox<String> jcbGenerosPreferidos;
    private javax.swing.JList<String> jlGenerosMenosPreferidos;
    private javax.swing.JList<String> jlGenerosPreferidos;
    private javax.swing.JSpinner jsAño;
    private javax.swing.JSpinner jsEdad;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
}
